In [43]:
#import cvs
import numpy as np
import matplotlib.pyplot as plt

data1 = np.loadtxt("montreal_temperature_2012.dat")
#the data has increasing temperatures, starting from a cold(-7.4) 
#to the middle of the year (max 22.3) and goes back down to a cold -3.5
data2 = np.loadtxt("toronto_temperature_2012.dat")
#the data has increasing temperatures, starting from a chilly(-1.7) 
#to the middle of the year, a hot (max 24.3) and goes back down to a chilly 0.8
data3 = np.loadtxt("vancouver_temperature_2012.dat")
#the data has increasing temperatures, starting from a breezy(3.6) 
#to the middle of the year (max 19) and goes back down to a breezy-chilly 4.4

print(data1)
print(data2)
print(data3)

plt.plot(data1, label='Montreal')
plt.plot(data2, label='Toronto')
plt.plot(data3, label='Vancouver')
plt.xlabel('Month')
plt.ylabel('Average monthly Temperature (Celcius)')
plt.title('2012 average monthly temperatures (100523629)')
plt.legend()
plt.show()

[ -7.4  -4.7   3.1   6.8  15.9  20.   22.3  22.2  16.   10.8   0.5  -3.5]
[ -1.7  -0.3   6.7   7.3  16.6  20.6  24.3  21.6  16.4  10.2   3.5   0.8]
[  3.6   4.8   5.6   9.6  12.2  14.3  17.7  19.   15.4  10.5   7.2   4.4]
